kind: pipeline
type: docker
name: default

clone:
  depth: 1

trigger:
  branch:
    - pages
  event:
    - push

steps:
  - name: deploy
    image: alpine:3.23.2
    volumes:
      - name: site
        path: /site
    commands:
      - rm -rf /site/*
      - cp -r ./* /site/

volumes:
  - name: site
    host:
      path: /home/ubuntu/docs.hmcl.net/www
