kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
- name: build
  image: ruby:3.4
  environment:
    JEKYLL_ENV: production
    BUNDLE_PATH: vendor/bundle
  commands:
    - bundle config mirror.https://rubygems.org https://mirrors.cloud.tencent.com/rubygems
    - bundle install --verbose
    - bundle exec jekyll build --trace --verbose
  volumes:
  - name: dist
    path: /drone/src/_site
  - name: vendor
    path: /drone/src/vendor
  - name: jekyll-cache
    path: /drone/src/src/.jekyll-cache
  when:
    branch: [main]

volumes:
- name: dist
  host:
    path: /home/ubuntu/docs.hmcl.net/www
- name: vendor
  host:
    path: /home/ubuntu/docs.hmcl.net/cache/vendor
- name: jekyll-cache
  host:
    path: /home/ubuntu/docs.hmcl.net/cache/jekyll-cache
