kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
- name: build
  image: ruby:3.4
  environment:
    JEKYLL_ENV: production
    BUNDLE_PATH: vendor/bundle
  commands:
    - "git -c http.sslVerify=false -c http.extraHeader=\"Host: git.hmcl.net\" clone --branch main --depth 1 https://host.docker.internal/huanghongxun/HMCL-docs.git HMCL-docs"
    - cd HMCL-docs
    - bundle config mirror.https://rubygems.org https://mirrors.cloud.tencent.com/rubygems
    - bundle install --verbose
    - bundle exec jekyll build --trace --verbose
  volumes:
  - name: dist
    path: /drone/src/HMCL-docs/_site
  - name: vendor
    path: /drone/src/HMCL-docs/vendor
  - name: jekyll-cache
    path: /drone/src/HMCL-docs/.jekyll-cache
  when:
    branch: [main]

volumes:
- name: dist
  host:
    path: /home/ubuntu/docs.hmcl.net/www
- name: vendor
  host:
    path: /home/ubuntu/docs.hmcl.net/cache/vendor
- name: jekyll-cache
  host:
    path: /home/ubuntu/docs.hmcl.net/cache/jekyll-cache
