kind: pipeline
type: docker
name: default

clone:
  depth: 1

trigger:
  branch:
    - pages
  event:
    - push

steps:
  - name: deploy
    image: alpine
    volumes:
      - name: site
        path: /site
    commands:
      - apk add --no-cache rsync
      - rsync -rtv --delete --exclude .git ./ /site/

volumes:
  - name: site
    host:
      path: /home/ubuntu/docs.hmcl.net/www
