kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: build
    image: node:24-alpine
    environment:
      PUBLIC_SITE_URL: "https://docs.hmcl.net"
    commands:
      - npm install
      - npm run build
    volumes:
      - name: dist
        path: /drone/src/dist
      - name: node_modules
        path: /drone/src/node_modules
    when:
      branch: [main]

volumes:
  - name: dist
    host:
      path: /home/ubuntu/docs.hmcl.net/www
  - name: node_modules
    host:
      path: /home/ubuntu/docs.hmcl.net/cache/node_modules
