appearance_color:
  type: radio
  default: light
  options:
    - light
    - dark
    - auto
appearance_color_switcher:
  type: radio
  default: enable
  options:
    - enable
    - disable
appearance_skin:
  type: multi-radio
  children:
    light:
      default: default
    dark:
      default: dark
  options:
    - default
    - air
    - aqua
    - contrast
    - dark
    - dirt
    - neon
    - mint
    - plum
    - sunrise
    - catppuccin_latte
    - catppuccin_mocha
