appearance_color:
  type: radio
  default: light
  options:
    - light
    - dark
    - auto
appearance_skin:
  type: multi-radio
  children:
    light:
      default: default
    dark:
      default: dark
  options:
    - default
    - air
    - aqua
    - contrast
    - dark
    - dirt
    - neon
    - mint
    - plum
    - sunrise
