cache_dir: .jekyll-cache/zh-TW
include:
  - _pages
  - "*.zh-TW.md"
  - "*.zh-TW.json"
exclude:
  - assets/
  - scripts/
  - LICENSE
  - "*.md"
  - "*.json"
locale: zh-TW
title: HMCL 文檔
head_scripts:
  - /assets/js/theme.zh-TW.js
build: true
