cache_dir: .jekyll-cache/en
include:
  - _pages
  - "*.en.md"
  - "*.en.json"
exclude:
  - assets/
  - scripts/
  - LICENSE
  - "*.md"
  - "*.json"
locale: en
title: HMCL Document
head_scripts:
  - /assets/js/theme.en.js
build: true
