name: test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Test
        run: git --no-pager log --oneline -n 10
